name: Validate terraform

on: 
  pull_request:
    branches: 
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Validate terraform
        run: |
          set -euo pipefail
          git diff origin/main --name-only --diff-filter=AM -z terraform | xargs -0 -rn1 dirname | sort -u | \
          while read i
          do
            sh -c "cd \"$i\" && echo -e \"\033[1;35m$i\033[0m\n\" && terraform init -input=false -backend=false && terraform validate"
          done